version: '2.4'

services:
  app:
    image: slack-clone:dev
    build:
      target: dev
      context: .
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - .:/bin/www/
    env_file: ./.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: testorm
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
