version: '2.4'

services:
  server:
    image: slack-clone-server:dev
    build:
      target: dev
      context: ./services/server
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    env_file: .env
    networks:
      internal:
      public:
        aliases:
          - ${SERVER_HOST}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./services/server:/bin/www/
      - ./node_modules:/bin/www/node_modules

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    networks:
      internal:
        aliases:
          - ${TYPEORM_HOST}
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    networks:
      internal:
        aliases:
          - ${REDIS_HOST}
    volumes:
      - redis_data:/data

networks:
  internal:
  public:

volumes:
  pg_data:
  redis_data:
